/*	This class creates the scrabble board by making use of a GridPane and the TilesFactory class.
 * This class was created because it is going to have EventHandlers added to it that would take care of 
 * all events generated by this board.
 * 
 * 	it is evolving, therefore methods and properties would be added to it as the project 
 * grows.
 */

package com.LetsPlay.ui;

import java.util.Collection;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;
import javafx.scene.Node;
import javafx.scene.layout.GridPane;

public class Board extends GridPane {
				private Hashtable <Node, Integer[]> tile_locations = new Hashtable<Node, Integer[]>();
				private Hashtable <Node, Integer[]> previous_tile_locations = new Hashtable<Node, Integer[]>();
				
				
				private Hashtable <Integer, String[]> played_tile = new Hashtable<Integer, String[]>();
				private Hashtable <Integer, String[]> previous_played_tile = new Hashtable<Integer, String[]>();
				
				private int row = 0;
				private int column = 1;
				
				//Constructor statement.
				public Board(){
					//Sets the dimensions of the board
					this.setPrefSize(593.50, 549);
					this.setGridLinesVisible(false);
					
					//Creating the board
					TilesFactory boardtiles = new TilesFactory();
					for(int rowindex = 0; rowindex < 15; rowindex++){
						for(int columnindex = 0; columnindex < 15; columnindex++){
							switch (rowindex){
							//Note: Some rows repeats.
							
							//Creates row 0 of the board.
							case 0:	switch (columnindex){
											case 0: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 3: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 7: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 11: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 14: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;					
											} break;
							
							//Creates row 1 of the board.
							case 1: switch (columnindex){
											case 1: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 5: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 9: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 13: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;	
											} break;
							
							//Creates row 2 of the board.
							case 2: switch (columnindex){
											case 2: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 6: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 8: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 12: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;
											
							//Creates row 3 of the board.				
							case 3: switch (columnindex){
											case 0: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 3: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 7: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 11: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 14: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;					
											} break;
									
							//Creates row 4 of the board.							
							case 4: switch (columnindex){
											case 4: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 10: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;
											
							//Creates row 5 of the board.											
							case 5: switch (columnindex){
											case 1: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 5: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 9: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 13: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;
							
							//Creates row 6 of the board.				
							case 6: switch (columnindex){
											case 2: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 6: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 8: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 12: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;			
											
							//Creates row 7 of the board.				
							case 7: switch (columnindex){
											case 0: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 3: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 7: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 11: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 14: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;	
											} break;
											
							//Creates row 8 of the board.					
							case 8: switch (columnindex){
											case 2: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 6: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 8: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 12: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;				
								
							//Creates row 9 of the board.			
							case 9: switch (columnindex){
											case 1: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 5: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 9: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 13: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;				
											
							//Creates row 10 of the board.				
							case 10: switch (columnindex){
											case 4: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 10: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;				
							
							//Creates row 11 of the board.				
							case 11: switch (columnindex){
											case 0: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 3: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 7: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 11: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 14: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;					
											} break;					
											
							//Creates row 12 of the board.				
							case 12: switch (columnindex){
											case 2: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 6: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 8: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 12: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;
											
							//Creates row 13 of the board.				
							case 13: switch (columnindex){
											case 1: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 5: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 9: this.add(boardtiles.createTripleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 13: this.add(boardtiles.createDoubleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;	
											} break;
							
							//Creates row 14 of the board.				
							case 14: switch (columnindex){
											case 0: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 3: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 7: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 11: this.add(boardtiles.createDoubleLetterScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											case 14: this.add(boardtiles.createTripleWordScore(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex);break;
											default: this.add(boardtiles.createEmptyBoardTile(Integer.toString(rowindex) + " " + Integer.toString(columnindex)), columnindex, rowindex); break;
											} break;
							default: break;
									
						}
							
									
											
						}
					}
					//This Iterator enables us get the location of the children in
					//the GridPane so as to ensure easy removal and placement of the 
					//tiles in the game board.
					Iterator<Node> temp = this.getChildren().iterator();
					while(temp.hasNext() == true){
						Node temp2 = temp.next();
						Integer[] location = new Integer[2];
						location[0] = GridPane.getRowIndex(temp2);
						location[1] = GridPane.getColumnIndex(temp2);
						this.tile_locations.put(temp2, location);
						this.previous_tile_locations.putAll(this.tile_locations);
					}
				}

				
				
				//Replaces a given node with another node.
				public void placeTile(Node tile_to_place, Node tile_on_board){
						
						//Gets the location of the Node to be replaced.
						Integer[] temp = this.tile_locations.get(tile_on_board);
						
						//Add the tile at the location of the deleted tile.
						this.add(tile_to_place, temp[this.column], temp[this.row]);
						
						
						Integer[] location = new Integer[2];
						location[0] = GridPane.getRowIndex(tile_to_place);
						location[1] = GridPane.getColumnIndex(tile_to_place);
						this.tile_locations.put(tile_to_place, location);
						/****************************************************************
						 * This part of the code updates the played_tile structure with *
						 * the string value of the tile placed on the board. 			*
						 ****************************************************************/
						
						
						/*Checks if a tile has been placed on this row before.
						 *if not, it places the tile on the row and adds it to the 
						 *played_tile structure.
						 */
						if (this.played_tile.containsKey(temp[this.row]) == false){
							String letters_in_row[] = new String[15];
							letters_in_row[temp[this.column]] = tile_to_place.getId().substring(0, 1); 
							this.played_tile.put(temp[this.row], letters_in_row);
							
							//else it modifies the row and updates it.
						} else{
							String letters_in_row[] = this.played_tile.get(temp[this.row]);
							letters_in_row[temp[this.column]] = tile_to_place.getId().substring(0, 1);
							this.played_tile.put(temp[this.row], letters_in_row);
						}
						
				}
				
				//Saves the current state of the board.
				public void saveState(){
						this.previous_tile_locations.putAll(this.tile_locations);
						this.previous_played_tile.putAll(this.played_tile);
				}
				
				//Overrides the current state of the board with its previous state.
				public void undoCurrentState(){
						this.played_tile.putAll(this.previous_played_tile);
						this.getChildren().clear();
						
						Collection<Integer[]> node_locations = this.previous_tile_locations.values();
						Iterator<Integer[]> node_iterator = node_locations.iterator();
						Enumeration<Node> nodes = this.previous_tile_locations.keys();
						while (nodes.hasMoreElements()){
							 Integer location[] = node_iterator.next();
							 Node node = nodes.nextElement();
							 this.add(node, location[this.column], location[this.row]);
						}
				}
				
}
